"""Add auth fields to User

Revision ID: 8c757daccfa3
Revises: 
Create Date: 2025-11-15 20:05:51.422363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c757daccfa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_driver_auth_api_keys'))

    op.drop_table('driver_auth')
    op.drop_table('driver_session')
    with op.batch_alter_table('driver_auths', schema=None) as batch_op:
        batch_op.create_index('idx_driver_auth_api_keys', ['api_key', 'previous_api_key'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('daily_pass_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active_driver', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_daily_pass_expires'), ['daily_pass_expires'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_daily_pass_expires'))
        batch_op.drop_column('is_active_driver')
        batch_op.drop_column('daily_pass_expires')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    with op.batch_alter_table('driver_auths', schema=None) as batch_op:
        batch_op.drop_index('idx_driver_auth_api_keys')

    op.create_table('driver_session',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('driver_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('last_location_update', sa.DATETIME(), nullable=True),
    sa.Column('last_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), nullable=True),
    sa.Column('current_lat', sa.FLOAT(), nullable=True),
    sa.Column('current_lng', sa.FLOAT(), nullable=True),
    sa.Column('last_delivery_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('suspicious_activity', sa.BOOLEAN(), nullable=True),
    sa.Column('suspicious_reason', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_auth.driver_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_auth',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('driver_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_active', sa.DATETIME(), nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('api_key_expires', sa.DATETIME(), nullable=False),
    sa.Column('previous_api_key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('max_daily_deliveries', sa.INTEGER(), nullable=True),
    sa.Column('allowed_ip_ranges', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('verification_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('successful_deliveries', sa.INTEGER(), nullable=True),
    sa.Column('rating_sum', sa.FLOAT(), nullable=True),
    sa.Column('rating_count', sa.INTEGER(), nullable=True),
    sa.Column('on_time_deliveries', sa.INTEGER(), nullable=True),
    sa.Column('total_deliveries', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('driver_id'),
    sa.UniqueConstraint('previous_api_key')
    )
    with op.batch_alter_table('driver_auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_driver_auth_api_keys'), ['api_key', 'previous_api_key'], unique=False)

    # ### end Alembic commands ###
